'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class LoginPage

	''' <summary>
	''' Head1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ProgressControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

	''' <summary>
	''' UPPopupWindowControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UPPopupWindowControl As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

	''' <summary>
	''' PopupWindowControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PopupWindowControl As Global.DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl

	''' <summary>
	''' viewImageControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected viewImageControl As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

	''' <summary>
	''' viewCaptionControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected viewCaptionControl As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

	''' <summary>
	''' UPEI control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UPEI As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

	''' <summary>
	''' ErrorInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	''' <summary>
	''' Table1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Table1 As Global.System.Web.UI.WebControls.Table

	''' <summary>
	''' TableRow2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' UPVSC control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UPVSC As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

	''' <summary>
	''' viewSiteControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
'INSTANT VB NOTE: The variable viewSiteControl was renamed since Visual Basic does not allow class members with the same name:
	Protected viewSiteControl_Renamed As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

	''' <summary>
	''' TableRow3 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableRow3 As Global.System.Web.UI.WebControls.TableRow

	''' <summary>
	''' TableCell4 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableCell4 As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' PopupActions control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PopupActions As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder
End Class
