'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class NestedFrameControl

	''' <summary>
	''' UPToolBar control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UPToolBar As Global.DevExpress.ExpressApp.Web.Templates.XafUpdatePanel

	''' <summary>
	''' ToolBar control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ToolBar As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' viewSiteControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected viewSiteControl As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl
End Class
